### ISSUE TITLE
Todo: notes to create

### ISSUE THREAD

**Issue by patheard** [patheard/covid-alert-server-staging-notes#1]
Terraform to doc:
- [x] certificates.tf
- [x] cloudfront.tf
- [x] cloudwatch.tf
- [ ] codedeploy.tf
- [x] ecr.tf
- [x] ecs.tf
- [x] elasticache.tf
- [x] iam.tf
- [ ] in-app-metrics.tf
- [x] kinesis.tf
- [x] kms.tf
- [x] lb.tf
- [x] mc-api-gateway.tf
- [x] mc-lambda.tf
- [x] mc-waf.tf
- [x] metrics.tf
- [x] networking.tf
- [x] rds.tf
- [x] route53.tf
- [x] s3.tf
- [x] secrets.tf
- [x] shield.tf
- [x] sns.tf
- [x] vpc_flow_log.tf
- [x] waf.tf

**Comment by patheard** [comment]
Omitting metrics and code deploy.
